package org.example.enums;

public enum EventMessageType {
    SHORT_LINK_ADD,
    SHORT_LINK_ADD_LINK,
    SHORT_LINK_ADD_MAPPING,
    SHORT_LINK_DELETE,
    SHORT_LINK_DELETE_LINK,
    SHORT_LINK_DELETE_MAPPING,
    SHORT_LINK_UPDATE,
    SHORT_LINK_UPDATE_LINK,
    SHORT_LINK_UPDATE_MAPPING,
}
